### PR TITLE
Quick Fix Icon + Refactoring of StatementAssist

### PR DESCRIPTION
**Pull request by fidley**
Icons for each of the QuickFixes (same) added, to let people know, if this is standard or custom. It should be easier for bugs reporting.
2021-12-17_13h38_54
2021-12-17_13h18_55

### CODE REVIEW

**Comment by MDagni** [comment]
Loved it 👍

**Comment by g-back** [comment]
Note that you have re-added all the .class files that I removed 😄

**Comment by fidley** [comment]
I'm too old for this 🤣 I'll try to fix this now

**Comment by fidley** [comment]
@g-back maybe a hint how you have done it?

**Comment by g-back** [comment]
https://devconnected.com/how-to-clear-git-cache/

Essentially

```
git rm -r - - cached bin
```
/bin being the bin folder that contains the class files (don't remember exactly what it's called)

**Comment by fidley** [comment]
thanks, should be OK now ;)

**Pull request merged**
