### PR TITLE
Refactor Full-Line to In-Line Comments + additional cleanup/refactoring

### LINKED ISSUE #28: Replace full line comment with in-line comment
Replace comments that start with `*` at the start of the line with inline-comments `"`
Unlike Full-Line Comments, Inline-comments are automatically indented, making them (imo) a lot easier to read.

Single Line or whole file (whole file: setting to be enabled)
Should be done easily with Regex since `*` has to be first character of line.

Will try this myself (if you give the ok)

### PR DESCRIPTION
**Pull request by g-back**
- Full-Line to In-Line functionality is now based on the selected code (similar to "remove all abap comments in selection" (closes #28)

- some renaming of methods, typo fixes
- rename of constants to conform to java coding standards (upper case and snake case)

The renames may be controversial, I'd understand if you'd want me to remove that from this PR, let me know

### CODE REVIEW

**Comment by fidley** [comment]
No problem for the refactoring. Fine for me :)

**Comment by fidley** [comment]
check the PR on my installation and then I'll merge and build when everyghings fine.
Thanks a lot!

**Comment by fidley** [comment]
Some minor issue I found during the tests, could you take a look on them?
1. We recevie the QuickFix to replace the full line comments in the selected area even if there is no selection. Of course after usage it does not work.
2. When you have a dot in the comment at the end it is left somehow. It should be deleted as well
fullLineComments
3. Not sure if this behaviour is OK? It removes the comment and commented code until 1st dot. Was this done like this on purpose?
fullLineComments2

**Comment by fidley** [comment]
> In 2 and 3 you are using a fix that already exists in the current version, not the one I'm adding in this PR 😅
> 
> Unless this PR changed the behaviour of that fix?
haha, true seems to be added by me in the past..... funny 😂🤣 I need to remind myself what was the goal 😂

**Comment by g-back** [comment]
But yeah i noticed that too, we can refractor it in the future 🙂

**Comment by g-back** [comment]
1. Should be fixed now!

**Comment by fidley** [comment]
Thanks
Will build new version in the evening :)

**Comment by fidley** [comment]
Sorry for the delay, but when I opened the code in Eclipse I started directly the refactoring and of course some of my previous quick fixes started not to work correctly. I probaly need some time tomorrow still to find all issues then I'll build.

I need to learn also how to do all the process corectly, means to check the PRs of others while I still have my own changes on the way. this could speed up things.

Sorry once again @g-back.

**Comment by fidley** [comment]
I've deployed plugin to the update side. Could you please test it this works for you?

**Comment by fidley** [comment]
@g-back Don't know if I asked, do you have Twitter and/or LinkedIn handle?

**Comment by g-back** [comment]
I do, but I don't really post anything there 🙂
What for, if I may ask?

**Comment by fidley** [comment]
To let SAP Community know about your input into the plugin 😊

**Pull request merged**
