### PR TITLE
new feature: sort data declarations; bugfix split data statements

### PR DESCRIPTION
**Pull request by lukas-mb**
- #58 (order in preferences)
- bugfix SplitToSeveralStatements (if there are empty rows)

### CODE REVIEW

**Comment by fidley** [comment]
Perfect. I will do review later on and I'll approve when I'll test it successful (and deploy to update site for others)!

Thanks!

**Comment by fidley** [comment]
I see the ordering is working nice, but I have one remark -> it does not work if you don't have the declaration under one DATA statement
Here it works
image

Here not
image

Are you able to make it work also with selected code if all concurrent statements are of the same type (ex. DATA)?

**Comment by lukas-mb** [comment]
Ahh... totally forgotten this case. Will implement this asap :)

**Comment by fidley** [comment]
Take your time 😁

**Comment by lukas-mb** [comment]
Any thoughts on how to sort declarations like this?

image

I'm not sure what the best logic would be... maybe activate the sorting just for single statements, so it is considering the single declarations until there are multiple declarations within one DATA. Here for example it would sort just `lv_maktx`, `lt_lips` and `lv_objky`, then sort the next 'block' `ls_lips` and `go_salv_table` and so on. 

Would you also consider inline declarations?

**Comment by fidley** [comment]
Normally inline declaration are done in different place than top of method, program, so I would not focus on them.
For the rest I see two possibilities:

1. - Sort everything, does not matter if they are inside one DATA statement or not
2. - sort only those which are linked under one DATA: statement. 

 I guess preferable would be the 1st version, but maybe it is good to give developer the right to decide? New parameter or two quick fixes, one for each option?

**Comment by lukas-mb** [comment]
I agree with inline declarations - will store them below the other declarations if a user would use them in this area... you never know.

And I also like the idea of an additional quick fix👍🏼

**Comment by fidley** [comment]
Perfect ;)

**Pull request merged**
